package:
  name: oslo.utils
  version: "2.2.0"

source:
  fn: oslo.utils-2.2.0.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.utils/oslo.utils-2.2.0.tar.gz
  md5: 2da2d34bc9384869294e5a9fc1b92aa8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oslo.utils = oslo.utils:main
    #
    # Would create an entry point called oslo.utils that calls oslo.utils.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3,<2.0

  run:
    - python
    - six >=1.9.0
    - babel >=1.3
    - iso8601 >=0.1.9
    - oslo.i18n >=1.5.0
    - monotonic >=0.1
    - pytz >=2013.6
    - netaddr >=0.7.12
    - netifaces >=0.10.4
    - debtcollector >=0.3.0

test:
  # Python imports
  imports:
    - oslo_utils.encodeutils
    - oslo_utils.eventletutils
    - oslo_utils.excutils
    - oslo_utils.fileutils
    - oslo_utils.netutils
    - oslo_utils.timeutils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'Oslo Utility library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
